### PR TITLE
Use JetBrains Toolbox Shell Script, when available

### PR DESCRIPTION
**Pull request by aik099**
See #57

### CODE REVIEW

**Comment by Bozzified** [comment]
Got this error

error-58

**Comment by aik099** [comment]
## Short story

I've pushed a fix. Please change `toolbox_shell_script: 'PhpStorm.cmd'` into `toolbox_shell_script: 'pstorm.cmd'` in the `run_editor.js` file. It should work this time.

## Long story

I've just installed JetBrains Toolbox to see what it creates in the `c:\Users\username\AppData\Local\JetBrains\Toolbox\scripts\` folder. I have these files in there:

* `PhpStorm` - double clicking reports an error (inside it has `#!/usr/bin/env bash`)
* `PhpStorm.cmd` - double clicking opens PhpStorm

My guess is that you've customized the default shell script name. And the `.cmd` needs to be used (so not just `pstorm`, but `pstorm.cmd`). I've updated PR to reflect both issues.

**Comment by Bozzified** [comment]
> ## Short story
> I've pushed a fix. Please change `toolbox_shell_script: 'PhpStorm.cmd'` into `toolbox_shell_script: 'pstorm.cmd'` in the `run_editor.js` file. It should work this time.
> 
> ## Long story
> I've just installed JetBrains Toolbox to see what it creates in the `c:\Users\username\AppData\Local\JetBrains\Toolbox\scripts\` folder. I have these files in there:
> 
> * `PhpStorm` - double clicking reports an error (inside it has `#!/usr/bin/env bash`)
> * `PhpStorm.cmd` - double clicking opens PhpStorm
> 
> My guess is that you've customized the default shell script name. And the `.cmd` needs to be used (so not just `pstorm`, but `pstorm.cmd`). I've updated PR to reflect both issues.

Sorry had some stuff to take care of. I'll check it out but yeah I did customize it cause it used to be pstorm and along the lines they changed it but I got used to pstorm. I'll check it now but it seems you figured out it.

**Comment by Bozzified** [comment]
> ## Short story
> I've pushed a fix. Please change `toolbox_shell_script: 'PhpStorm.cmd'` into `toolbox_shell_script: 'pstorm.cmd'` in the `run_editor.js` file. It should work this time.

Not sure if I'm blind, but I can't find `toolbox_shell_script` in the new run_editor.js

**Comment by aik099** [comment]
> Not sure if I'm blind, but I can't find `toolbox_shell_script` in the new run_editor.js

This was done in the
https://github.com/aik099/PhpStormProtocol/pull/58/commits/20c7431dc1611d1b8dbbf84b13945eeceab908a7 commit of this PR.

> It actually works without changing anything in run_editor.js, so I'm guessing you figured it out without changing?

If we forget the new `settings.toolbox_shell_script` setting, then I've just added `.cmd` to the end of the executed toolbox script. Probably JetBrains Toolbox can handle both `pstorm.cmd` and `PhpStorm.cmd`.

Please double check, that following cases work and I'll merge this PR:

1. opening a single file without specifying a line number using `phpstorm://` url
2. opening a single file with a line number specified using `phpstorm://` url
3. opening a directory using `phpstorm://` URL

.

**Comment by Bozzified** [comment]
> > Not sure if I'm blind, but I can't find `toolbox_shell_script` in the new run_editor.js
> 
> This was done in the [20c7431](https://github.com/aik099/PhpStormProtocol/commit/20c7431dc1611d1b8dbbf84b13945eeceab908a7) commit of this PR.
> 
> > It actually works without changing anything in run_editor.js, so I'm guessing you figured it out without changing?
> 
> If we forget the new `settings.toolbox_shell_script` setting, then I've just added `.cmd` to the end of the executed toolbox script. Probably JetBrains Toolbox can handle both `pstorm.cmd` and `PhpStorm.cmd`.
> 
> Please double check, that following cases work and I'll merge this PR:
> 
> 1. opening a single file without specifying a line number using `phpstorm://` url
> 2. opening a single file with a line number specified using `phpstorm://` url
> 3. opening a directory using `phpstorm://` URL
> 
> .

Sorry Alex it's the holidays so I'm all over the place with some work and personal things before New year..

I just tested it.. Works great.. opens the proper file from the url and jumps to the line number. I used this latest commit. I'm using pstorm.cmd in Toolbox.

Everything seems to be good.

**Comment by aik099** [comment]
Merged. Thank you.

**Pull request merged**
