### PR TITLE
shell.AppActivate using ProcessId instead window_title...

### PR DESCRIPTION
**Pull request by oriceon**

### CODE REVIEW

**Comment by oriceon** [comment]
I`ll came back with more changes...

**Comment by aik099** [comment]
@oriceon , interesting idea, but what are the benefits in contrast to the window title activation approach?

**Comment by oriceon** [comment]
For me, with the window title didn`t act as it should.
And I found that window title was "project name - opened.php", and also with that name, didn't work.
I managed to open the application after with that title but only with nircmd ...

Also, i want to push a new pull request with some changes. I want to get process path and strip some config options....

**Comment by aik099** [comment]
That indeed would be useful, because I imagine right now people are editing `run_editor.js` after every PhpStorm upgrade.

**Pull request closed without merging**
